os: linux
dist: bionic
language: minimal
services:
- docker
env:
  jobs:
  - DOCKER_BASE_IMAGE=multiarch/ubuntu-core:arm64-bionic INIT_SCRIPT=ubuntu-bionic-prepare.sh
  - DOCKER_BASE_IMAGE=multiarch/alpine:arm64-v3.9 INIT_SCRIPT=alpine-prepare.sh PIP_IGNORE="lxml"
    TARBALL_SUFFIX=alpine
before_install:
- docker run --rm --privileged multiarch/qemu-user-static:register
script:
- docker run --rm -v $(pwd)/qemu-aarch64:/usr/bin/qemu-aarch64 -v $(pwd)/seafile-build:/opt
  -e TRAVIS="$TRAVIS" -e SEAFILE_IGNORE_PIP="$PIP_IGNORE" -it ${DOCKER_BASE_IMAGE}
  /bin/sh -c "cd /opt && ./${INIT_SCRIPT} && ./build_seafile.sh"
after_success:
- '[ -n "$TARBALL_SUFFIX" ] && ./rename.sh $TARBALL_SUFFIX'
- ls -lh seafile-build/output
deploy:
  provider: releases
  overwrite: true
  file_glob: true
  file: seafile-build/output/*.tar.gz
  on:
    repo: hanwckf/seafile-arm64-build
    tags: true
  skip_cleanup: 'true'
  api_key:
    secure: bhudbSdNNYhQF/7khiioK5QGXTRGPINRS1ZN0nInZEETvb2j6mQUXXOFk2VMXurYLPsDppANDwH/zFvwO2jVH8sYvQJ+1iM/TXxHibAhEVQj9vMrMlHpRRyWRa/19Wt/lrHoyvYJ1qmDixkwKdyIK0mR8YEV/uvRq82qG/kaj3fTcpm4RcRehaZLUzRHHvxyk4xZb/V57kB56G+17sWHtVfTWdKWzhxn2qS51qjf7ru262snK8MlH04U6UZjHcf399G8IlKImcJ/2+ZfhsdR8f1lWr5MH6ezT0/OOETBR85Qo4DQ97eVvP6VgexwntlZD6l+UK51IO//HaJt066ExzkNhqvK47hoqOU2sV8YqWIKalB5igw0Pn3f3O3hS0fnnB7LglNz8K5OiXsaFHAewiU2rKbeVXsuOZ1MqG4WbwaU3xg0aoAhb33ySHv6DkRe4bIsxygBiCqumrSVOGEBZdS4R0bLUrpYRjPTObAg2ApHhUpWNE15+s7xTyZHuEhsM6COj0eNdp2s5t1FB15kihA6QhuGqLYo12siY35jRHjREjDcTlGr3Wdwv91y+Yl05w4cUL5dzAlbbBg9kI4xtRqooEbVt+d66OBMAB5LVqrf0EGZOCTHhbZ+K6f7ZjGxh7Hd6t/YF+kgIX8//Sxft0Q4tn+gTh8aPdnm8+70tWY=
