os: linux
dist: bionic
language: minimal
services:
  - docker

env:
  jobs:
  - DOCKER_BASE_IMAGE=multiarch/ubuntu-core:arm64-bionic INIT_SCRIPT=ubuntu-bionic-prepare.sh
  - DOCKER_BASE_IMAGE=multiarch/alpine:arm64-v3.12 INIT_SCRIPT=alpine-prepare.sh TARBALL_SUFFIX="alpine"

before_install:
- docker run --rm --privileged multiarch/qemu-user-static:register

script:
- docker run --rm
  -v $(pwd)/qemu-aarch64:/usr/bin/qemu-aarch64
  -v $(pwd)/seafile-build:/opt
  -e TRAVIS="$TRAVIS"
  -it ${DOCKER_BASE_IMAGE}
  /bin/sh -c "cd /opt && ./${INIT_SCRIPT} && ./build_seafile.sh"

after_script:
- '[ -n "$TARBALL_SUFFIX" ] && ./rename.sh $TARBALL_SUFFIX'
- ls -lh seafile-build/output

deploy:
  provider: releases
  api_key:
    secure: GYB1ttIow2fHniSkjoiBFB4G6MzeNhyIPV+qI/9KoIhzLlda2962RwEGbovv8tlTkZD7Y2/NbfcOnoURnXYzgoNP+7deYYtrW9AMbl9LuDNFD+s08FWvVgxM6UGDu+SplN8SFjcgAuuCzoYdOAHKM4UjkHulIgXDE8rlcBWZuQ7dmJdq2BBGKnsDPkMqlVxDJGTBSl0Ge4ubECPLtqhf6Pf1HotCVStfTffW0USMQQ+fnUhHTCp1mDx9Ept7C+YJ66NIBiVHGdOfPvHV7XergJJKPtxOw8p/P3SG37znkaZ3CBN+zafcWzuVr2IHJqiGjkIvaIJzvMBrAxuRA0o88XJsxt+D8js575avaev9AqK2VlgUaa7qZI2+VbzxJdXd7rRHc6mZf06ETwHPMeudzMymAjc9GUEXzDvZRZsEp1UsK6BKIxOKE4TnJz9PyTlHqQLG+CnM5K8cPYq57Ye38UTrpHURbmFcyhQKKJp/Hc7BrXnWVbTFAey/8dTjN8vjok7mAtw2jrS5oMLi3JdOFBjbyIjTpohKpwVGCvGsRonRbk39JkYN7lWnz/AgciRyjflQ4cmmULg3HTHa5RXhtrety2qqPAGuNzQgbGYUonl+bWdpb5rdYNPVxI1w7kMlqihWv6Rrk1ureNNQnIB/fZX3x/4KZyw+CGtrz8Udr7k=
  overwrite: true
  file_glob: true
  file: seafile-build/output/*.tar.gz
  on:
    repo: hanwckf/seafile-aarch64-build
    tags: true
  skip_cleanup: 'true'

